image: node:latest

pages:
  stage: deploy
  script:
    - npm i
    - npm run build
    - mkdir public
    - mv dist/* public/.
    - mv assets/*.png public/.
  artifacts:
    paths:
      - public
  only:
    - master
