language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
  - ".cache"
deploy:
  provider: heroku
  on: master
  app: three-dog-bot
  api_key:
    secure: gmihbJt5MVjpmMWMQJkV4Z+iw+Bw2z3fK8PUw34V/8a1+JNhNAten3DnCQU3i0H6B8pG5CbiWbWErCiJ+Ybt7QNZcMgSW4q5RFy2dReybz3zpgDBeTZ6qtLrQ7M2lCKC4raJboKqXf2y3qj/8bKoyEHHwfEGUpoS1ogKykcLioPsvMfVJIVsi+yi83Dnjd3+2adJQTI9L5uHbDMu/NzhzV7wDGW2OwUj3YoFikz6KZI+eOZLOM5LBKoGwkZyJM2vEtapAesOEo9WGBR64lN9ZI9acvN6vgr2rHeH9Ac77aY4rRFI+6shvIkfHci+Dpu7DFkI5F//gPDnbJx1CXZfvn9xiLYgXWsu1qqlUogxwy0K1CQByD6iyas3K5jHFr81SZLD0zKwKiE4G78RRXjgFMzii1hfz82DjbsH/+Q07+LGV+fvUI+QAshyudMyFg09MPa/rqbV1+7AGXIvMGpZ4QYNLcXaA2+lScDba6WlAWkpFExU+ky19OobVON0spLmLnWg/V+j/Ji5DX+v3Sq6ULQn+pYOyg3B+NxOZF4kD7jSQKvOw7nPejNI0XAs/T74ONfRO+1rVdZ4wBAIAVfTAzZ44cM6RtvG940EQ1Yvf1Yo0YOxNhBNFmk8bfEI44NcIq6Oh4VmUZ0yWBbGXMJ3mpooKjrryWQ3bRrNxVsU3PY=
